<?php
declare(strict_types=1);
namespace jasonwynn10\DimensionAPI;

use pocketmine\event\level\LevelLoadEvent;
use pocketmine\event\Listener;
use pocketmine\level\format\io\LevelProviderManager;
use pocketmine\plugin\PluginBase;

class Main extends PluginBase implements Listener {
	public function onLoad() {
		LevelProviderManager::addProvider(AnvilDimensionProvider::class);
		//LevelProviderManager::addProvider(LevelDBDimensionProvider::class); // TODO
	}
	public function onEnable() {
		parent::onEnable(); // TODO: Change the autogenerated stub
	}
	public function onLevelLoad(LevelLoadEvent $event) : void {
		$provider = $event->getLevel()->getProvider();
		if($provider instanceof AnvilDimensionProvider/* or $provider instanceof LevelDBDimensionProvider*/) {
			// TODO
		}
	}

}