--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonw4331/NativeDimensions
projects:
  NativeDimensions:
    path: ""
    icon: "icon.gif"
    excludeDirs:
      - .github
      - build
    excludeFiles:
      - .gitignore
      - CONTRIBUTING.md
      - SECURITY.md
      - phpstan.neon.dist
      - phpstan-baseline.php
      - .php-cs-fixer.php
...
